from pydantic import BaseModel, Field
from typing import List, Literal, TypedDict

MetaQAType = Literal[
    "Language",
    "Person",
    "Text",
    "Date",
    "Number",
    "Organization",
    "CreativeWork",
]


class MetaSubQueryItem(TypedDict):
    query: str
    answer_type: MetaQAType


class MetaSubQueryResponse(TypedDict):
    sub_queries: List[MetaSubQueryItem]


class SubQueryResponse(BaseModel):
    sub_queries: List[str] = Field(
        ...,
        description="List of sub-queries generated by the LLM.",
    )


class RerankerResponse(BaseModel):
    reranked_combos: List[str] = Field(
        ...,
        description="The reranked combos based on subquery .",
    )
